M48
; DRILL file {KiCad 8.0.1} date 2024-04-10T16:57:43+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-10T16:57:43+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X13.97Y2.54
X15.24Y50.8
X66.04Y35.56
X66.04Y7.62
M30
